### ISSUE TITLE
VSC extension recheck

### ISSUE THREAD

**Issue by zolomatok** [DanielXMoore/Civet#15]
I'm _really really happy_ about the existence of a real time checker in the form of the VS Code plugin.
I know it's in an early state.

Often times it gets stuck, showing errors for lines that don't exist anymore.
I noticed that its memory is bound to file names, so if I delete `test.civet`, but rename another file to `test.civet`, it will instantly start to show the phantom errors in that file.

Is there a way to ask the extension to forget everything and recheck the whole file from scratch? Maybe a keyboard shortcut? Is that possible?

_PS: off topic, but love that we have a file icon now_

**Comment by STRd6** [comment]
There currently isn't a specific command to restart the Civet LSP. I should add that... it might make a great 1st contribution.

In the meantime I often use `Ctrl+Shift+P` then `Developer: Restart Extension Host` to restart all VSCode extensions

**Comment by zolomatok** [comment]
Ah, gotcha, thanks for the tip!
I'm happy to give implementing this a try.
Can you give me a couple pointers about what tools you use for plugin development?

**Comment by STRd6** [comment]
The LSP code is here: https://github.com/DanielXMoore/Civet/tree/master/lsp

Here's MS docs on extensions: https://code.visualstudio.com/api

To build:

```bash
cd Civet/lsp
yarn install
yarn build
```

That will create a `civet-0.2.2.vsix` file in the `lsp` directory. To test it right click on it in the VSCode file browser and choose "Install Extension VSIX"

For this feature there are two parts: adding a command to the extension `package.json` and then triggering the restart. Adding the command should be easy but I'm not sure off the top of my head how easy triggering the restart would be.

Let me know if you have any questions!

**Comment by STRd6** [comment]
Fixed in https://github.com/DanielXMoore/Civet/pull/23 LSP v0.2.8

**Comment by zolomatok** [comment]
Thanks @STRd6!

I started looking into this after your post, then realised `Developer: Restart Extension Host` doesn't actually fix my problem, so I gave up on implementing it in the extension. Then promptly forgot about mentioning it, sorry about that!

**Comment by zolomatok** [comment]
Thanks @STRd6!

I started looking into this after your post, then realised `Developer: Restart Extension Host` doesn't actually fix my problem, so I gave up on implementing it in the extension. Then promptly forgot about mentioning it, sorry about that!
