### ISSUE TITLE
Parser doesn't understand arguments that have `new() => T` types

### ISSUE THREAD

**Issue by vshesh** [DanielXMoore/Civet#562]
```
class Test
  test<T extends Element>(n: new() => T) 
    return 1 
```

is enough to trigger the error

**Comment by edemaine** [comment]
Fixed in 0.6.11!

**Comment by vshesh** [comment]
@edemaine  

Still getting an error with the following: 
```
export class Element 
  readonly name: string; 
  assets: string[];
  @(parse: (...args: any[]) => Tag, public nest: Nesting, public subElements: SubElement[]) {
    @name = makename(parse.name)
    @assets = []
  }

  sub<T extends X>(clazz: abstract new (...args: any) => T) { 
    return this.children.filter((x): x is T => x instanceof clazz) 
  } 

```


error:
```
/Users/vishesh/repos/gluejs/elements.civet:96:36 Failed to parse
Expected:
	Whitespace /[\s]+/
	JSMultiLineComment "/*"
	CoffeeHereCommentStart /###(?!#)/
	JSSingleLineComment /\/\/(?!\/)[^\r\n]*/
	TypeBinaryOp "|"
	TypeBinaryOp "&"
	TypeConditional "extends"
	Equals "="
	NonNewlineWhitespace /[ \t]+/
	InlineComment "/*"
	Comma ","
	ParameterElementDelimiter /[)}]/
	EOL /\r\n|\n|\r|$/
Found: "new"
```

is this a vscode extension issue?

**Comment by edemaine** [comment]
@vshesh Thanks for the report. I didn't realize `abstract new` was also valid, so it didn't make it into the grammar. Will add support shortly.

**Comment by edemaine** [comment]
Should be fixed in 0.6.14!
