### ISSUE TITLE
Cannot find module 'node:readline'

### ISSUE THREAD

**Issue by zolomatok** [DanielXMoore/Civet#8]
Given a simple program:

`var something = "else"`

when compiling, I get the following error:

```
Error: Cannot find module 'node:readline'
Require stack:
- /Users/zolo/project/ftl/node_modules/@danielx/civet/dist/civet
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/Users/zolo/project/ftl/node_modules/@danielx/civet/dist/civet:13:12)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/Users/zolo/project/ftl/node_modules/@danielx/civet/dist/civet' ]
}
```

Civet is installed locally (not globally) and is ran like so:

`civet ./something.civet ./something.ts`

**Comment by STRd6** [comment]
@zolomatok thanks for opening this issue!

What version of node are you using?

The current `civet` CLI only operates on stdin/out so the way to invoke it would be 

```bash
civet < ./something.civet > ./something.ts
```

**Comment by edemaine** [comment]
The `node:` prefix was [introduced in Node 16](https://2ality.com/2021/12/node-protocol-imports.html) for `require`. We could remove the prefix and it would work for earlier Nodes...

**Comment by STRd6** [comment]
@zolomatok I published a possible fix in v0.4.19-pre.7 give it a shot!

@edemaine https://github.com/DanielXMoore/Civet/commit/2ce2ff70892d48f7a5566da4265f4149782704e8

**Comment by zolomatok** [comment]
@STRd6 Thanks so much. Yeah, I'm running `Node v14.17.3`, that must be it!
I updated Civet, but unfortunately, it's still not quite right.
I don't get an error anymore, compilation just seemingly hangs indefinitely.

**Comment by edemaine** [comment]
@zolomatok What operating system are you using? You're piping the input via `<`?

**Comment by zolomatok** [comment]
@edemaine 
Oh, I'm so sorry, I missed the piping bit!
It works no problem now!
